# Generated by Django 6.0.4 on 2026-04-27 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Email address used for login', max_length=254, unique=True)),
                ('full_name', models.CharField(help_text='Full name of the admin user', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Contact phone number', max_length=20)),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('protocol_admin', 'Protocol Admin'), ('protocol_member', 'Protocol Member')], db_index=True, default='admin', help_text='Role determines access level and permissions', max_length=20)),
                ('bound_device_id', models.CharField(blank=True, help_text='Device fingerprint/ID for protocol member device binding', max_length=255, null=True)),
                ('admin_permissions', models.JSONField(blank=True, default=dict, help_text='Granular permission flags for Admin role, set by Superadmin')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can access Django admin site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'admin_users',
                'ordering': ['-created_at'],
            },
        ),
    ]
