# Generated by Django 6.0.4 on 2026-04-27 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., "2025/2026 First Semester"', max_length=100)),
                ('start_date', models.DateField(help_text='Semester start date')),
                ('end_date', models.DateField(help_text='Semester end date — archiving triggers at this date')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one semester should be active at a time')),
                ('is_archived', models.BooleanField(default=False, help_text='Locked after archiving — no further edits allowed')),
                ('registration_open', models.BooleanField(default=False, help_text='Controls whether student self-registration is accessible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GeoFenceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Chapel latitude coordinate', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Chapel longitude coordinate', max_digits=10)),
                ('radius_meters', models.PositiveIntegerField(default=200, help_text='Radius in meters from chapel center for geo-fence')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(help_text='Superadmin who last updated the geo-fence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofence_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geo-Fence Configuration',
                'verbose_name_plural': 'Geo-Fence Configuration',
                'db_table': 'geofence_config',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('midweek', 'Midweek'), ('sunday', 'Sunday'), ('special', 'Special')], help_text='Type of service: midweek, sunday, or special', max_length=10)),
                ('service_group', models.CharField(choices=[('S1', 'Service 1'), ('S2', 'Service 2'), ('S3', 'Service 3'), ('all', 'All Students')], help_text='Service group (S1/S2/S3) or "all" for special services', max_length=5)),
                ('name', models.CharField(blank=True, default='', help_text='Optional descriptive name for the service', max_length=200)),
                ('scheduled_date', models.DateField(db_index=True, help_text='Date the service is scheduled')),
                ('window_open_time', models.DateTimeField(help_text='Attendance window opens at this time (UTC)')),
                ('window_close_time', models.DateTimeField(help_text='Attendance window closes at this time (UTC)')),
                ('signout_required', models.BooleanField(default=False, help_text='If True, both sign-in and sign-out are required for valid attendance')),
                ('capacity_cap', models.PositiveIntegerField(default=500, help_text='Maximum number of students for this service group')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Cancelled services are excluded from total required count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(help_text='Semester this service belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.semester')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['scheduled_date', 'window_open_time'],
                'indexes': [models.Index(fields=['semester', 'is_cancelled'], name='idx_service_semester_active')],
            },
        ),
    ]
