# Generated by Django 4.2.16 on 2026-04-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='service_group_capacities',
            field=models.JSONField(blank=True, default=dict, help_text='Capacity cap per service group for student auto-assignment. E.g., {"S1": 500, "S2": 500, "S3": 500}'),
        ),
    ]
