# Generated by Django 4.2.16 on 2026-05-02 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_signout_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapelEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('tag', models.CharField(choices=[('midweek', 'Midweek'), ('sunday', 'Sunday'), ('special', 'Special'), ('conference', 'Conference'), ('announcement', 'Announcement')], default='special', max_length=20)),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='event_flyers/%Y/%m/')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Activates the sitewide countdown banner on the landing page.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = shown first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chapel Event',
                'verbose_name_plural': 'Chapel Events',
                'db_table': 'chapel_events',
                'ordering': ['sort_order', 'event_date'],
            },
        ),
    ]
