# Generated by Django 4.2.16 on 2026-05-02 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_chapelevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('speaker', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('service_date', models.DateField()),
                ('tag', models.CharField(choices=[('midweek', 'Midweek'), ('sunday', 'Sunday'), ('special', 'Special')], default='sunday', max_length=20)),
                ('audio_file', models.FileField(blank=True, help_text='Upload an audio file (mp3, wav, m4a). Use this OR video_url, not both.', null=True, upload_to='sermons/audio/%Y/%m/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL. Used when no audio file is uploaded.', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='sermons/thumbs/%Y/%m/')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Approximate duration in minutes', null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sermon',
                'verbose_name_plural': 'Sermons',
                'db_table': 'sermons',
                'ordering': ['-service_date'],
            },
        ),
    ]
