# Generated by Django 6.0.4 on 2026-04-27 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_type', models.CharField(choices=[('old', 'Old Student'), ('new', 'New Student')], help_text='Old students have matric numbers; new students get system IDs', max_length=5)),
                ('matric_number', models.CharField(blank=True, db_index=True, help_text='Required for old students. Updated later for new students.', max_length=50, null=True)),
                ('system_id', models.CharField(db_index=True, help_text='Auto-generated unique ID for new students', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text='Stored in title case (auto-capitalized)', max_length=255)),
                ('full_name_normalized', models.CharField(db_index=True, help_text='Lowercase version for fuzzy matching', max_length=255)),
                ('phone_number', models.CharField(db_index=True, help_text='Required. Checked for exact duplicates.', max_length=20)),
                ('department', models.CharField(help_text='Student department', max_length=100)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level')], help_text='Academic level: 100, 200, 300, or 400', max_length=5)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Student gender', max_length=10)),
                ('profile_photo', models.ImageField(blank=True, help_text='Profile display photo (separate from face samples)', null=True, upload_to='profile_photos/%Y/%m/')),
                ('face_registered', models.BooleanField(default=False, help_text='True when minimum 3 face samples are approved')),
                ('service_group', models.CharField(blank=True, choices=[('S1', 'Service 1'), ('S2', 'Service 2'), ('S3', 'Service 3')], help_text='Assigned service group (S1/S2/S3)', max_length=5, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Active when face registered and no duplicate flags')),
                ('duplicate_flag', models.BooleanField(db_index=True, default=False, help_text='Flagged for Superadmin review if potential duplicate detected')),
                ('duplicate_details', models.JSONField(blank=True, default=dict, help_text='Details of duplicate detection matches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Set when manually added by admin/superadmin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(help_text='Current semester scope', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='services.semester')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_file', models.FileField(help_text='Face capture image file — stored in non-public directory', upload_to='')),
                ('embedding_vector', models.JSONField(default=list, help_text='DeepFace Facenet512 embedding vector (512-dimensional)')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Auto-evaluated on capture', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, help_text='Specific rejection reason shown to student', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(help_text='Semester scope — deleted on archive', on_delete=django.db.models.deletion.CASCADE, related_name='face_samples', to='services.semester')),
                ('student', models.ForeignKey(help_text='Student this face sample belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='face_samples', to='students.student')),
            ],
            options={
                'db_table': 'face_samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['semester', 'service_group', 'is_active'], name='idx_student_service_pool'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('matric_number__isnull', False)), fields=('matric_number', 'semester'), name='unique_matric_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('phone_number', 'semester'), name='unique_phone_per_semester'),
        ),
    ]
