# Generated by Django 6.0.4 on 2026-05-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, help_text='Student faculty', max_length=255, null=True),
        ),
    ]
