# Generated by Django 6.0.4 on 2026-06-26 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_studentaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Free-text complaint as typed by the student')),
                ('category', models.CharField(choices=[('scan_failed', 'Scan Failed'), ('wrong_status', 'Wrong/Missing Attendance Status'), ('sync_issue', 'Sync Issue'), ('account_access', 'Account Access'), ('other', 'Other')], default='other', help_text='Assigned by triage after submission — not chosen by the student', max_length=20)),
                ('flagged_services', models.JSONField(blank=True, default=list, help_text='Service UUIDs triage determined the complaint relates to, if any')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('auto_resolved', 'Auto-Resolved'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=15)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('resolution_type', models.CharField(choices=[('none', 'None'), ('explained', 'Explained'), ('fix_needed', 'Fix Needed')], default='none', help_text='Set by deterministic diagnostics, never by the LLM', max_length=10)),
                ('suggested_fix', models.JSONField(blank=True, help_text='e.g. {"action": "backdate", "service_ids": [...], "backdate_type": "valid"} — pre-fills the existing attendance edit/backdate form for one-click admin approval', null=True)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_draft_reply', models.TextField(blank=True, default='')),
                ('admin_reply', models.TextField(blank=True, default='', help_text='What is actually shown to the student — defaults to the auto-generated explanation/draft, editable by admin')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Null for auto-resolved tickets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issue_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student who submitted the report', on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='students.student')),
            ],
            options={
                'db_table': 'issue_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='idx_issue_status_severity'), models.Index(fields=['student', 'status'], name='idx_issue_student_status')],
            },
        ),
    ]
