# Generated by Django 6.0.4 on 2026-06-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='student_followup',
            field=models.TextField(blank=True, default='', help_text='Justification/proof the student gave in response to an awaiting_proof request — e.g. why they believe they attended despite no record existing. Required before a missing-record fix can be suggested to admin, to deter "free attendance" claims.'),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='resolution_type',
            field=models.CharField(choices=[('none', 'None'), ('explained', 'Explained'), ('awaiting_proof', 'Awaiting Proof'), ('fix_needed', 'Fix Needed')], default='none', help_text='Set by deterministic diagnostics, never by the LLM', max_length=15),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('awaiting_proof', 'Awaiting Proof'), ('in_review', 'In Review'), ('auto_resolved', 'Auto-Resolved'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=15),
        ),
    ]
