# Generated by Django 6.0.4 on 2026-06-26 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issuereport_student_followup_and_more'),
        ('students', '0003_studentaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuereport',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='ai_draft_reply',
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='student_followup',
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='Admin-facing quick-glance summary of the thread, kept in sync by triage'),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='category',
            field=models.CharField(choices=[('scan_failed', 'Scan Failed'), ('wrong_status', 'Wrong/Missing Attendance Status'), ('sync_issue', 'Sync Issue'), ('account_access', 'Account Access'), ('other', 'Other')], default='other', help_text='Assigned by triage after the first message — not chosen by the student', max_length=20),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='student',
            field=models.ForeignKey(help_text='Student who opened this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='students.student'),
        ),
        migrations.CreateModel(
            name='IssueMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('student', 'Student'), ('ai', 'AI'), ('admin', 'Admin')], max_length=10)),
                ('text', models.TextField(blank=True, default='')),
                ('attachment', models.ImageField(blank=True, help_text='Evidence photo the student attached — e.g. proof they were present', null=True, upload_to='issue_attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Set when sender=admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_messages', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='issues.issuereport')),
            ],
            options={
                'db_table': 'issue_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
