# Generated by Django 6.0.4 on 2026-04-27 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='Device fingerprint/ID of the marking device', max_length=255)),
                ('gps_lat', models.DecimalField(decimal_places=7, help_text='Latitude at time of marking', max_digits=10)),
                ('gps_lng', models.DecimalField(decimal_places=7, help_text='Longitude at time of marking', max_digits=10)),
                ('signed_in_at', models.DateTimeField(help_text='Timestamp when student was signed in')),
                ('signed_out_at', models.DateTimeField(blank=True, help_text='Timestamp when student was signed out (if required)', null=True)),
                ('is_valid', models.BooleanField(default=True, help_text='Computed based on service signout_required rule')),
                ('is_offline_record', models.BooleanField(default=False, help_text='True if this record was synced from an offline queue')),
                ('is_backdated', models.BooleanField(default=False, help_text='True if created via late resumption backdating')),
                ('backdate_type', models.CharField(blank=True, choices=[('valid', 'Valid'), ('excused', 'Excused')], help_text='Set for backdated records: "valid" or "excused"', max_length=10, null=True)),
                ('sync_validation_result', models.CharField(blank=True, help_text='Result of offline sync validation (e.g., "accepted", "rejected: out-of-window")', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol_member', models.ForeignKey(help_text='Protocol member who performed the marking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service this attendance belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='services.service')),
                ('student', models.ForeignKey(help_text='Student who was marked', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-signed_in_at'],
                'indexes': [models.Index(fields=['service', 'is_valid'], name='idx_attendance_service_valid'), models.Index(fields=['student', 'is_valid'], name='idx_attendance_student_valid')],
                'constraints': [models.UniqueConstraint(fields=('student', 'service'), name='unique_student_per_service')],
            },
        ),
    ]
