# Generated by Django 6.0.4 on 2026-04-27 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_index=True, help_text='Action identifier, e.g., ATTENDANCE_EDIT, STUDENT_DELETE, DEVICE_REBIND', max_length=50)),
                ('target_type', models.CharField(help_text='Type of the affected entity, e.g., Student, Service, AttendanceRecord', max_length=50)),
                ('target_id', models.UUIDField(db_index=True, help_text='UUID of the affected record')),
                ('previous_value', models.JSONField(blank=True, help_text='Snapshot of the record before the change', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Snapshot of the record after the change', null=True)),
                ('reason_note', models.TextField(blank=True, default='', help_text='Mandatory for manual edits and backdating')),
                ('device_id', models.CharField(blank=True, default='', help_text='Device used to perform the action', max_length=255)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude at time of action', max_digits=10, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude at time of action', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of the action — append-only, no record can be modified')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='idx_audit_action_time'), models.Index(fields=['actor', 'created_at'], name='idx_audit_actor_time')],
            },
        ),
    ]
